### ISSUE TITLE
Recommendation Engine

### ISSUE THREAD

**Issue by SarahZLipeles** [TheoLipeles/BrooklyGameExchange#57]

**Comment by joedotjs** [comment]
Cool, I'm on it! Right after I find the missing n.

**Comment by SarahZLipeles** [comment]
actions: 
    rated 5 stars
    rated 4 stars
    purchased history
    Developer
    Genre
    Average Price Paid
    Date Released
    ¿Language Parsing?
––––––––––––––––––––––––––––––––––––
    Dev's Own Games
    rated 2 stars
    rated 1 star

**Comment by SarahZLipeles** [comment]
recommendations based on user
recommendations based on game
